spring:
  application:
    name: movieApi

  datasource:
    url: jdbc:mysql://localhost:3306/moviePulseDb?useSSL=false
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  poster: posters/

base:
  url: "http://localhost:8080"
